routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\GuruController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', [LoginController::class, 'index']);
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::get('/register', [RegisterController::class, 'index']);
Route::post('/register', [RegisterController::class, 'register'])->name('register');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('layouts.index');
    });
    Route::resource('guru', GuruController::class);
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

app/Models/Guru.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Guru extends Model
{
    use HasFactory;
    protected $table = 'guru';
    protected $fillable = ['nama', 'nip', 'jabatan', 'pendidikan', 'tempat_lahir', 'tanggal_lahir', 'agama', 'telp', 'alamat', 'foto'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GuruController.php
<?php

namespace App\Http\Controllers;

use App\Models\Guru;
use Illuminate\Http\Request;

class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Guru::latest()->get();
        return view("pages.guru.index", compact(['data']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.guru.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "nama" => 'required|min:4',
            "nip" => 'required|integer|min:7',
            "jabatan" => 'required',
            "pendidikan" => 'required',
            "tempat_lahir" => 'required',
            "tanggal_lahir" => 'required',
            "agama" => 'required',
            "telp" => 'required|min:11',
            "alamat" => 'required',
            "file" => 'mimes:jpg,png,jpeg:max:1024'
        ]);
        // dd($request->all());
        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $fileName = time() . "." . $file->getClientOriginalExtension();
            $file->move(public_path('images'), $fileName);
            $request->request->add(['foto' => $fileName]);
        }

        Guru::updateOrCreate(['id' => $request->id], $request->all());
        $message = !empty($request->id) ? 'data berhasil di rubah' : 'data berhasil di tambahkan';
        return redirect(route('guru.index'))->with('success', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Guru $guru)
    {
        return view('pages.guru.detail', compact(['guru']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Guru $guru)
    {
        return view('pages.guru.edit', compact(['guru']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guru $guru)
    {
        $guru->delete();
        return back()->with('success', 'Data guru berhasil dihapus');
    }
}

resources/views/layouts/includes/_footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

resources/views/layouts/includes/_header.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Latihan UJIKOM</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('assets/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('assets/bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ asset('assets/bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('assets/dist/css/AdminLTE.min.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('assets/dist/css/skins/_all-skins.min.css') }}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{{ asset('assets/bower_components/morris.js/morris.css') }}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{ asset('assets/bower_components/jvectormap/jquery-jvectormap.css') }}">
  <!-- Date Picker -->
  <link rel="stylesheet"
    href="{{ asset('assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('assets/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ asset('assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
  {{-- Datatable --}}
  <link rel="stylesheet"
    href="{{ asset('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  @yield('css')

  <!-- Google Font -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

resources/views/layouts/includes/_script.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('assets/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('assets/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('assets/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
{{-- <script src="{{ asset('assets/bower_components/raphael/raphael.min.js') }}"></script> --}}
{{-- <script src="{{ asset('assets/bower_components/morris.js/morris.min.js') }}"></script> --}}
<!-- Sparkline -->
<script src="{{ asset('assets/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('assets/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('assets/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('assets/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('assets/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('assets/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('assets/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('assets/dist/js/adminlte.min.js') }}"></script>

{{-- DataTable --}}
<script src="{{ asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@yield('script')
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{ asset('assets/dist/js/pages/dashboard.js') }}"></script> --}}
<!-- AdminLTE for demo purposes -->
{{-- <script src="{{ asset('assets/dist/js/demo.js') }}"></script> --}}

resources/views/layouts/includes/_sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('assets/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ auth()->user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                            class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            {{-- <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li> --}}
            <li>
                <a href="{{ route('guru.index') }}">
                    <i class="fa fa-th"></i> <span>Guru</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-green">new</small>
                    </span>
                </a>
            </li>
            {{-- <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                </ul>
            </li> --}}
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html>

@include('layouts.includes._header')

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        @include('layouts.includes._navbar')
        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.includes._sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Dashboard
                    <small>Control panel</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Dashboard</li>
                </ol>
            </section>


            <!-- Main content -->
            <section class="content">
                @if (session('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <strong>Success !</strong> {{ Session::get('success') }}
                </div>
                @elseif (session('error'))
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <strong>Error !</strong> {{ Session::get('error') }}
                </div>
                @endif

                <!-- Small boxes (Stat box) -->
                @yield('content')

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        @include('layouts.includes._footer')

        <!-- Control Sidebar -->

        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    @include('layouts.includes._script')
</body>

</html>

resources/views/pages/guru/create.blade.php
@extends('layouts.index')
@section('content')
<div class="row">
    <div class="col-md-6">
        <form action="{{ route('guru.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    <input type="text" class="form-control" name="nama" placeholder="Nama" value="{{ old('nama') }}">
                </div>
                @error('nama')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-book"></i></span>
                    <input type="text" class="form-control" name="nip" placeholder="NIP" value="{{ old('nip') }}">
                </div>
                @error('nip')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                    <input type="text" class="form-control" name="jabatan" placeholder="Jabatan"
                        value="{{ old('jabatan') }}">
                </div>
                @error('jabatan')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-graduation-cap"></i></span>
                    <input type="text" class="form-control" name="pendidikan" placeholder="Pendidikan"
                        value="{{ old('pendidikan') }}">
                </div>
                @error('pendidikan')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-bank"></i></span>
                    <input type="text" class="form-control" name="tempat_lahir" placeholder="Tempat Lahir"
                        value="{{ old('tempat_lahir') }}">
                </div>
                @error('tempat_lahir')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    <input type="date" class="form-control" name="tanggal_lahir" placeholder="Tanggal Lahir"
                        value="{{ old('tanggal_lahir') }}" data-inputmask="&quot;mask&quot;:&quot;(12-12-1990)&quot;"
                        data-mask="">
                </div>
                @error('tanggal_lahir')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="agama">Agama</label>
                <select name="agama" id="agama" class="form-control" value="{{ old('agama') }}">
                    <option>Islam</option>
                    <option>Kristen</option>
                    <option>Hindu</option>
                    <option>Budha</option>
                    <option>Lainnya</option>
                </select>
                @error('agama')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                    <input type="text" class="form-control" name="telp" placeholder="No Telp" value="{{ old('telp') }}"
                        data-inputmask="&quot;mask&quot;:&quot;(12-12-1990)&quot;" data-mask="">
                </div>
                @error('telp')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
                    <textarea name="alamat" cols="30" rows="10" class="form-control">{{ old('alamat') }}</textarea>
                </div>
                @error('alamat')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <label for="foto">Photo</label>
                    <input type="file" name="file" class="form-control" value="{{ old('file') }}">
                    <p>Silahkan input photo guru</p>
                </div>
                @error('file')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div>
                <a href="{{ route('guru.index') }}" class="btn btn-warning btn-sm">Batal</a>
                <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/guru/detail.blade.php
@extends('layouts.index')
@section('content')
<div class="row">
    <div class="col-md-3">
        <div class="box box-primary">

            <div class="box-body box-profile">
                <img src="{{ asset('images/'.$guru->foto) }}" alt="" class="profile-user-img img-responsive img-circle">
                <h3 class="profile-username text-center"> {{ $guru->name }} </h3>
                <p>
                <h4 class="text-muted text-center">{{ $guru->jabatan }} </h4>
                </p>
                <strong><i class="fa fa-book margin-r-5">NIP :</i></strong> {{ $guru->nip }}
                <hr>
                <strong><i class="fa fa-book margin-r-5">Pendidikan :</i></strong> {{ $guru->pendidikan }}
                <hr>
                <strong><i class="fa fa-book margin-r-5">Tempat Lahir :</i></strong> {{ $guru->tempat_lahir }}
                <hr>
                <strong><i class="fa fa-book margin-r-5">Tanggal Lahir :</i></strong> {{ $guru->tanggal_lahir }}
                <hr>
                <strong><i class="fa fa-book margin-r-5">No Telp :</i></strong> {{ $guru->telp }}
                <hr>
                <strong><i class="fa fa-book margin-r-5">Alamat :</i></strong> {{ $guru->alamat }}
                <hr>
                <a href="/guru" class="btn btn-success btn-block"><b>CLOSE</b></a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/guru/edit.blade.php
@extends('layouts.index')
@section('content')
<div class="row">
    <div class="col-md-6">
        <form action="{{ route('guru.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="hidden" value="{{ $guru->id }}" name="id">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    <input type="text" class="form-control" name="nama" placeholder="Nama" value="{{ $guru->nama }}">
                </div>
                @error('nama')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-book"></i></span>
                    <input type="text" class="form-control" name="nip" placeholder="NIP" value="{{ $guru->nip }}">
                </div>
                @error('nip')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                    <input type="text" class="form-control" name="jabatan" placeholder="Jabatan"
                        value="{{ $guru->jabatan }}">
                </div>
                @error('jabatan')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-graduation-cap"></i></span>
                    <input type="text" class="form-control" name="pendidikan" placeholder="Pendidikan"
                        value="{{ $guru->pendidikan }}">
                </div>
                @error('pendidikan')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-bank"></i></span>
                    <input type="text" class="form-control" name="tempat_lahir" placeholder="Tempat Lahir"
                        value="{{ $guru->tempat_lahir }}">
                </div>
                @error('tempat_lahir')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    <input type="date" class="form-control" name="tanggal_lahir" placeholder="Tanggal Lahir"
                        value="{{ $guru->tanggal_lahir }}" data-inputmask="&quot;mask&quot;:&quot;(12-12-1990)&quot;"
                        data-mask="">
                </div>
                @error('tanggal_lahir')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="agama">Agama</label>
                <select name="agama" id="agama" class="form-control" value="{{ $guru->agama }}">
                    <option>Islam</option>
                    <option>Kristen</option>
                    <option>Hindu</option>
                    <option>Budha</option>
                    <option>Lainnya</option>
                </select>
                @error('agama')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                    <input type="text" class="form-control" name="telp" placeholder="No Telp" value="{{ $guru->telp }}"
                        data-inputmask="&quot;mask&quot;:&quot;(12-12-1990)&quot;" data-mask="">
                </div>
                @error('telp')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
                    <textarea name="alamat" cols="30" rows="10" class="form-control">{{ $guru->alamat }} </textarea>
                </div>
                @error('alamat')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div class="form-group">
                <div class="input-group">
                    <label for="foto">Photo</label>
                    <input type="file" name="file" class="form-control" value="{{ $guru->foto }}">
                    <p>Silahkan input photo guru</p>
                </div>
                @if (!empty($guru->foto))
                <img src="{{ asset('images/'.$guru->foto) }}" alt="" width="300">
                @endif
                @error('file')
                <div class="text-danger">{{$message }} </div>
                @enderror
            </div>
            <div>
                <a href="{{ route('guru.index') }}" class="btn btn-warning btn-sm">Batal</a>
                <button type="submit" class="btn btn-primary btn-sm">Simpan</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/guru/index.blade.php
@extends('layouts.index')
@section('content')
<div class="box">
    <div class="container">
        <h3 class="box-title"> <i class="fa fa-database"> Data Guru</i></h3>
        <div class="box-header">
            <a href="{{ route('guru.create') }} " class="btn btn-primary btn-sm pull-right"><i
                    class="fa fa-plus-square"> Tambah Guru</i></a>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="tabelGuru" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama</th>
                    <th>NIP</th>
                    <th>Alamat</th>
                    <th>Photo</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $key => $guru)
                <tr>
                    <td>{{ $key+1 }} </td>
                    <td>{{ $guru->nama }} </td>
                    <td>{{ $guru->nip }} </td>
                    <td>{{ $guru->alamat }} </td>
                    <td>
                        <img src="{{ asset('images/'.$guru->foto) }}" alt="" width="60">
                    </td>
                    <td>


                        <form action="{{ route('guru.destroy',['guru'=> $guru->id]) }}" method="POST"
                            id="deleteGuru-{{ $guru->id }}">
                            @method('DELETE')
                            @csrf
                        </form>
                        <a href="{{ route('guru.show',['guru'=> $guru->id]) }} " class="btn btn-success
                            btn-sm">Detail</a>
                        <a href="{{ route('guru.edit',['guru' => $guru->id]) }}" class="btn btn-warning btn-sm">Edit</a>
                        <button type="button" onclick="deleteItem({{ $guru->id }})"
                            class="btn btn-danger btn-sm">Delete</button>
                    </td>
                </tr>

                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('script')

<script>
    $(() =>{
        $('#tabelGuru').DataTable();
    })

    function deleteItem(id){
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
            if (result.isConfirmed) {
                $('#deleteGuru-'+id).get(0).submit();
            }
        })
    }
</script>
@endsection